// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD1mihg1uKW2oekMsqUg2TLbyVetqZpdk',
    appId: '1:617439898429:web:b3ba7b0e58677cf97bb354',
    messagingSenderId: '617439898429',
    projectId: 'csc-4360-activity-14',
    authDomain: 'csc-4360-activity-14.firebaseapp.com',
    storageBucket: 'csc-4360-activity-14.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtlvd7QDjDiGP1n6Tq1AJZEbetTjwm59M',
    appId: '1:617439898429:android:d2e8f875c08cec4c7bb354',
    messagingSenderId: '617439898429',
    projectId: 'csc-4360-activity-14',
    storageBucket: 'csc-4360-activity-14.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqbZXwaJbWFYue0id8L698Gcnsi2Pwn10',
    appId: '1:617439898429:ios:7193533b4192b07b7bb354',
    messagingSenderId: '617439898429',
    projectId: 'csc-4360-activity-14',
    storageBucket: 'csc-4360-activity-14.firebasestorage.app',
    iosBundleId: 'com.example.activity14',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqbZXwaJbWFYue0id8L698Gcnsi2Pwn10',
    appId: '1:617439898429:ios:7193533b4192b07b7bb354',
    messagingSenderId: '617439898429',
    projectId: 'csc-4360-activity-14',
    storageBucket: 'csc-4360-activity-14.firebasestorage.app',
    iosBundleId: 'com.example.activity14',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBD1mihg1uKW2oekMsqUg2TLbyVetqZpdk',
    appId: '1:617439898429:web:387a07829387b8a97bb354',
    messagingSenderId: '617439898429',
    projectId: 'csc-4360-activity-14',
    authDomain: 'csc-4360-activity-14.firebaseapp.com',
    storageBucket: 'csc-4360-activity-14.firebasestorage.app',
  );
}
